---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: simple-service
          image: fruit22/simple-service:v2
          ports:
            - name: web
              containerPort: 8000
  selector:
    matchLabels:
      app: my-app

