---
apiVersion: v1
kind: ConfigMap
metadata:
  name: crud-app-config-map
data:
  DATASOURCE_URL: jdbc:postgresql://postgres:5432/myapp
---
apiVersion: v1
kind: Secret
metadata:
  name: crud-app-secret
data:
  USERNAME: dXNlcg==
  PASSWORD: MTIzNDU2
